### ISSUE TITLE
I would like to inquire about the switch bootloader code

### ISSUE THREAD

**Issue by ryan1109** [Spacecraft-NX/sdloader#3]
**How this code is generated seems different from the code commented above. Very curious**  

about sign_bootloader.py.

**Comment by balika011** [comment]
compiled then encrypted with the bootloader key

**Comment by ryan1109** [comment]
thinks, Is it the assembly code that encrypts the comments above?  
Also, where is the bootloader key?

**Comment by ryan1109** [comment]
thinks.
